baseURL = 'http://suryapranav.github.io'
languageCode = 'en-us'
title = "Surya's Website"
theme = "sam"

[[params.mainMenu]]
    link = "/posts"
    text = "/writing/"

[[params.mainMenu]]
    link = "/intro"
    text = "/about-me/"

[[params.mainMenu]]
    link = "/about-me"
    text = "/interests/"

[[params.mainMenu]]
    link = "/hmm"
    text = "/interesting stuff/"

# [[params.mainMenu]]
#     link = "/humor"
#     text = "/humor/"

# [[params.mainMenu]]
#     link = "/dotfiles"
#     text = "/dotfiles/"
